"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var person_1 = require("./person");
var neo = new person_1.default('Neo', 18, 'Rong');
neo.greet();
console.log(neo.name, neo.age);
neo.age = 23;
console.log(neo.name, neo.age);
var tim = new person_1.default('Tim', 18);
tim.greet();
console.log(tim.name, tim.age);
